### ISSUE TITLE
Project.fromDir should infer name and version from the package.json

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/node-fixturify-project#23]

**Comment by stefanpenner** [comment]
I think we are https://github.com/stefanpenner/node-fixturify-project/blob/820956090fbed5ecacb32685f2d01f4047452178/index.ts#L98

**Comment by rwjblue** [comment]
I see that we reset them after reading the directory, but the `name` argument should be optional then.

**Comment by stefanpenner** [comment]
@rwjblue so `this.name = this.name || pkg.name` ?

**Comment by rwjblue** [comment]
At the time where we instantiate the `Project` we haven't read the `pkg` yet so I think we'd use a dummy name (like we use a dummy version of `'x.x.x'`) which would then get updated to the right value when we call `.readDir`.

**Comment by rwjblue** [comment]
At the time where we instantiate the `Project` we haven't read the `pkg` yet so I think we'd use a dummy name (like we use a dummy version of `'x.x.x'`) which would then get updated to the right value when we call `.readDir`.

**Comment by stefanpenner** [comment]
We can bifurcate  `fromDir` to support both the current API, and the proposed.

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/node-fixturify-project/pull/24
