### ISSUE TITLE
Drop `node-` from package name

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/node-fixturify-project#3]
Most of our other repos that have `node-` in the repo name do not have node- in the actual package name.

This tripped me up 🙃

**Comment by rwjblue** [comment]
And the README says `const Project = require('fixturify-project');` which is incorrect...

**Comment by stefanpenner** [comment]
shit. Let me re-release

**Comment by stefanpenner** [comment]
released as v1.0.0 🎉

**Comment by stefanpenner** [comment]
I've deprecated -> https://www.npmjs.com/package/node-fixturify-project
