### ISSUE TITLE
Repository copied without attribution

### ISSUE THREAD

**Issue by scalvert** [stefanpenner/node-fixturify-project#65]
I came across this repo: https://github.com/javascpdev/node-fixturify-project. It appears to be a direct copy of this repo, not a fork, with no attribution. The individual has also rewritten the commits to appear that they are the author.

I think we should submit a DMCA takedown notice.

https://github.com/contact/dmca 
https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice

cc/ @stefanpenner @ef4 @rwjblue @krisselden

**Comment by stefanpenner** [comment]
@scalvert good catch!

**Comment by stefanpenner** [comment]
I've reported the user to GH.
