### ISSUE TITLE
Node built-ins cause error in pure ESM tooling due to incorrectly transpiled require calls.

### ISSUE THREAD

**Issue by scalvert** [stefanpenner/node-fixturify-project#68]
I noticed this issue when updating to v5.x in a library that uses `vitest`, which itself uses `esbuild`. There's a [known issue](https://github.com/evanw/esbuild/issues/1921) with esbuild where built-in Node APIs are transpiled to require calls vs. import statements for ESM targets. This causes an issue when consuming those transpiled libraries.

Error:
<img width="1647" alt="Screen Shot 2022-04-18 at 8 46 25 AM" src="https://user-images.githubusercontent.com/180990/163834322-2ff73365-698c-4ec0-9368-2c93d309a2f1.png">

The line in question:
<img width="640" alt="Screen Shot 2022-04-18 at 8 47 27 AM" src="https://user-images.githubusercontent.com/180990/163834491-8b996159-2722-4234-b648-5f3a0a7f5f08.png">

The conversion of this library to tsup, which itself uses esbuild + rollup to output the esm target output, also has manifested this issue. This library doesn't exhibit the issue itself even though it also uses `vitest`, but downstream consumers do, as they're using the published output, which contains the issue.

Folks at Netlify also experienced this, and they've created [a PR](https://github.com/evanw/esbuild/pull/2067) to address it. Once that's merged we'll look to ensure the associated packages are subsequently updated once they find their way to the associated libraries.

**Comment by stefanpenner** [comment]
Thanks for keeping me in the loop and being proactive.
